services:
  - docker

script:
  - docker-compose build
  - docker-compose run authtables go test -race -coverprofile=coverage.txt -covermode=atomic -v
  - docker-compose run authtables go tool cover -html=coverage.txt -o coverage.html
  - docker-compose down
  - docker-compose up -d
  - docker-compose run authtables scripts/test
  - docker-compose down

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
