language: go
go:
  - 1.11.x
  - tip

services:
  - docker
  - redis-server

script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose run authtables go test -race -coverprofile=coverage.txt -covermode=atomic
  - ./scripts/test

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
