version: '3'

services:

    authtables:
      build: .
      image: mramshaw4docs/authtables:1.15.4
      ports:
       - "8080:8080"
      depends_on:
       - redis
      volumes:
       - ./coverage:/opt/authtables/coverage/
      env_file: .env
      command: /opt/authtables/authtables

    redis:
      image: redis:latest
      sysctls:
       net.core.somaxconn: 511
