version: '2'

services:

    authtables:
      build: .
      image: mramshaw4docs/authtables:1.11
      ports:
       - "8080:8080"
      volumes:
       - .:/opt/authtables
      depends_on:
       - redis
      env_file: .env

    redis:
      image: redis
