version: '3'

services:

    authtables:
      build: .
      image: mramshaw4docs/authtables:1.11
      ports:
       - "8080:8080"
      depends_on:
       - redis
      env_file: .env
      command: /opt/authtables/authtables

    redis:
      image: redis:latest
      sysctls:
       net.core.somaxconn: 1024
